project_id = "xahzovelzrdgpweymlqq"

[functions.api-proxy]
verify_jwt = false

[functions.health-monitor]
verify_jwt = false

[functions.houston-traffic]
verify_jwt = false

[functions.manage-secrets]
verify_jwt = false

[functions.rss-fetcher]
verify_jwt = false