// This file is automatically generated. Do not edit it directly.
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";

const SUPABASE_URL = "https://xahzovelzrdgpweymlqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhhaHpvdmVsenJkZ3B3ZXltbHFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2OTM0ODcsImV4cCI6MjA3MzI2OTQ4N30.vV5rIQO4sD24bCEx4iwPJFqaYyiHfQeG93aceKrVnTs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  },
);
